### PR TITLE
WIP: fix several bugs

### PR DESCRIPTION
**Pull request by wangliang1989**
@smousavi05

### CODE REVIEW

**Comment by wangliang1989** [comment]
After install EQT from sources, there are three directories: EQTransformer.egg-info/ build/ dist/.
I am new in Python.
Can I delete them?
If they can be deleted, I suggest the setup.py delete them.

**Comment by wangliang1989** [comment]
I suggest:

GS.CA06.00.HH1__20190901T000000Z__20190902T000000Z

change to

GS.CA06.00.HH1_20190901T000000Z_20190902T000000Z

**Comment by wangliang1989** [comment]
Have you tried to install on Centos. So many errors. Right now, I don't have enough time. But, I will fix any problem on Mac

**Comment by smousavi05** [comment]
No these changes are not necessary

**Pull request closed without merging**
